name: Terraform Module Tests

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*-*'
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Select the module you want to test'
        required: true
        type: choice
        options:
          - vpc
          - bastion
          - secrets
          - iam
          - eks
          - s3

permissions:
  id-token: write
  contents: read

jobs:
  terraform-test:
    name: Test Terraform Modules
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - name: Detect Module Directory
      id: detect-module
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          MODULE_NAME="${{ github.event.inputs.module_name }}"
        elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
          MODULE_NAME=$(echo "${GITHUB_HEAD_REF}" | cut -d '/' -f1)
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          MODULE_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///' | sed 's/-v[0-9.]*//')
        fi
        echo "module_name=${MODULE_NAME}" >> $GITHUB_ENV

    - name: Run Terraform init
      run: |
        cd ${{ env.module_name }}
        terraform init
  
    - name: Run Terraform Formatting Check
      run: |
        cd ${{ env.module_name }}
        terraform fmt -check -recursive 

    - name: Run Terraform Validation
      run: |
        cd ${{ env.module_name }}
        terraform validate

    - name: Install tflint
      run: |
        curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  
    - name: Run Terraform Lint
      run: |
        cd ${{ env.module_name }}
        tflint --recursive 
  
    - name: Install dependencies
      run: |
        cd ${{ env.module_name }}/tests
        if [ ! -f "go.mod" ]; then
          go mod init github.com/your-org/${{ env.module_name }}-tests
        fi
        go mod tidy -compat=1.23
  
    - name: Run Terratest
      run: |
        cd ${{ env.module_name }}/tests
        go test -v -timeout 30m