name: Terraform Module Tests

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*-*'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-test:
    name: Test Terraform Modules
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Detect Module Directory
      id: detect-module
      run: |
        if [[ "${GITHUB_REF}" == refs/pull/* ]]; then
          # Extract the module name from the branch name in the pull request
          MODULE_NAME=$(echo "${GITHUB_HEAD_REF}" | cut -d '/' -f1)
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          # Extract the module name based on the tag name
          MODULE_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///' | sed 's/-v[0-9.]*//')
        fi
        echo "module_name=${MODULE_NAME}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd ${{ env.module_name }}/tests
        if [ ! -f "go.mod" ]; then
          go mod init github.com/your-org/${{ env.module_name }}-tests
        fi
        go mod tidy -compat=1.23

    - name: Run Terratest
      run: |
        cd ${{ env.module_name }}/tests
        go test -v -timeout 30m