name: Terraform Module Tests

on:
  push:
    tags:
      - 'secrets-*'
      - 'bastion-*'
      - 'vpc-*'
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-test:
    name: Test Terraform Modules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Detect Module Directory
      id: detect-module
      run: |
        # Extract the module name based on the tag or pull request
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          MODULE_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///' | sed 's/-v[0-9.]*//')
        else
          # For pull requests, detect the modified directory
          MODULE_NAME=$(git diff --name-only origin/main | grep '/' | cut -d '/' -f1 | uniq | head -n 1)
        fi
        echo "module_name=${MODULE_NAME}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd terraform-modules/${{ env.module_name }}/tests
        go mod tidy

    - name: Run Terratest
      run: |
        cd terraform-modules/${{ env.module_name }}/tests
        go test -v -timeout 30m